apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: odf-policygenerator
placementBindingDefaults:
  name: binding-policy-odf
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  policySets:
    - odf-policyset
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
# ODF Policies - start
- name: policy-odf
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odf/policy-odf.yaml
- name: policy-odf-cluster
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-7 Software Firmware and Information Integrity
  dependencies:
    - name: policy-odf
  manifests:
    - path: input-odf/policy-odf-cluster.yaml
- name: policy-odf-status
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-7 Software Firmware and Information Integrity
  dependencies:
    - name: policy-odf
  manifests:
    - path: input-odf/policy-odf-status.yaml
  remediationAction: inform
# ODF Policies - end
policySets:
  - description: The ODF policy set applies several policies
      that install the OpenShift Data Foundation using best practices. This policy set is focused on 
      the components that install to every managed cluster.
    name: odf-policyset
    placement:
      placementPath: input/clusters-placement.yaml
